-- Astronomy Snowflake Schema

CREATE OR REPLACE TABLE ASTRO_RAW_UPLOADS (
    UPLOAD_ID STRING PRIMARY KEY,
    SOURCE_FILE STRING,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    ROW_COUNT NUMBER,
    COLUMN_SCHEMA VARIANT
);

CREATE OR REPLACE TABLE STARS_FACT (
    STAR_ID STRING,
    UPLOAD_ID STRING REFERENCES ASTRO_RAW_UPLOADS(UPLOAD_ID),
    LUMINOSITY FLOAT,
    TEMPERATURE FLOAT,
    METALLICITY FLOAT,
    AGE_MYR FLOAT,
    EMBEDDING ARRAY,
    CLUSTER_LABEL STRING,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE COSMIC_TWINS (
    HUMAN_ID STRING,
    STAR_ID STRING,
    SIMILARITY FLOAT,
    MATCHED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    NOTES STRING,
    PRIMARY KEY (HUMAN_ID, STAR_ID)
);

