-- Finance Snowflake Schema

CREATE OR REPLACE TABLE FINANCE_RAW_UPLOADS (
    UPLOAD_ID STRING PRIMARY KEY,
    SOURCE_FILE STRING,
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    ROW_COUNT NUMBER,
    SCHEMA_SUMMARY VARIANT
);

CREATE OR REPLACE TABLE MARKET_FACT (
    RECORD_ID STRING PRIMARY KEY,
    UPLOAD_ID STRING REFERENCES FINANCE_RAW_UPLOADS(UPLOAD_ID),
    TICKER STRING,
    TRADE_DATE DATE,
    CLOSE_PRICE NUMBER(18,4),
    VOLUME NUMBER,
    RETURN_1D FLOAT,
    VOLATILITY_30D FLOAT,
    RISK_SCORE FLOAT,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PORTFOLIO_METRICS (
    PORTFOLIO_ID STRING,
    AS_OF DATE,
    VAR_95 FLOAT,
    CVAR_95 FLOAT,
    MAX_DRAWDOWN FLOAT,
    SHARPE_RATIO FLOAT,
    PRIMARY KEY (PORTFOLIO_ID, AS_OF)
);

