-- Convenience views

CREATE OR REPLACE VIEW VW_ASTRO_CLUSTER_SUMMARY AS
SELECT
    CLUSTER_LABEL,
    COUNT(*) AS STAR_COUNT,
    AVG(AGE_MYR) AS AVG_AGE_MYR,
    AVG(LUMINOSITY) AS AVG_LUMINOSITY
FROM STARS_FACT
GROUP BY CLUSTER_LABEL;

CREATE OR REPLACE VIEW VW_FINANCE_RISK_SUMMARY AS
SELECT
    PORTFOLIO_ID,
    AS_OF,
    VAR_95,
    CVAR_95,
    SHARPE_RATIO
FROM PORTFOLIO_METRICS;

